# Generated by Django 5.2.8 on 2025-12-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineShop', '0002_product_description_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
